server:
  port: 8781

# 指定Eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-service
  # 配置redis信息
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  # 配置zipkin服务地址
  zipkin:
    base-url: http://localhost:9411/
  # 配置采用百分比，开发环境可以配置为1，表示解析所有请求，生产环境使用默认值
  sleuth:
    sampler:
      probability: 1

# 配置product-service服务调用的负载均衡策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 配置feign调用超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
  # 开启feign的hystrix支持
  hystrix:
    enabled: true

